### ISSUE TITLE
pnpm dev not starting a local server?

### ISSUE THREAD

**Issue by camdenvaughan** [OliverSpeir/astro-decap-ssg-netlify-identity#1]
Sorry to bother you with this, I am sure it is due something im doing wrong but I was trying to use this repo to play around with decap and I can only get it to build if i deploy it to netlify. This is my first time using pnpm so it might be due to that but, when I do pnpm dev I get this:
```
> decap-starter@0.0.1 dev C:\Users\camde\Projects\web\decap-test
> decap-server & astro dev

info: Decap CMS File System Proxy Server configured with C:\Users\camde\Projects\web\decap-test
info: Decap CMS Proxy Server listening on port 8081
```
or I get this if i do pnpm preview after doing build:
```
> decap-starter@0.0.1 preview C:\Users\camde\Projects\web\decap-test
> decap-server & astro preview

info: Decap CMS File System Proxy Server configured with C:\Users\camde\Projects\web\decap-test
info: Decap CMS Proxy Server listening on port 8081
```

then it just hanges there and the normal astro localhost:4321 doesn't work at all, I thought maybe I had to use localhost:8081, but that just displays a blank page with "Cannot GET /"

Everything works flawlessly when deployed so I figure its something I am messing up here.

**Comment by OliverSpeir** [comment]
Sorry about that this is because the dev script had syntax that only worked on macs
   `"dev": "decap-server & astro dev"` needs to become `"dev": "start decap-server & start astro dev"`
   
   Thank you for including the commands which showed you were on windows otherwise this wouldve taken me much longer to figure out, also if you have any questions feel free to message me on discord

**Comment by OliverSpeir** [comment]
I'll try to find a cross-platform command that works for this but for now I've edited the readme to make note of this and I think it will be easiest to just edit the command yourself

**Comment by camdenvaughan** [comment]
Hi I actually came to say I resolved this and saw you updated the readme, I don't know if it was the best way to solve it but I did it by adding a dependency called "concurrently" so i just installed it as a dependency using `pnpm add -D concurrently` then edited the commands to be `"dev": "concurrently \"decap-server\" \"astro dev\""`, and `"preview": "concurrently \"decap-server\" \"astro preview\"",`
For me this has been working flawlessly ever since I did that!

**Comment by camdenvaughan** [comment]
also thank you for this template it has been really useful!

**Comment by camdenvaughan** [comment]
I was actually going to add really quick the only reason I went the adding a dependency route over editing the comands to be `"start decap-server & start astro preview"` was becasue on window at least that would open two terminal windows each time instead of just running in my vs code terminal which functionally didn't matter, but it was a minor annoyance.
